### ISSUE TITLE
[Bug]: show exception if i config multiple sku in shopify management

### ISSUE THREAD

**Issue by tingxin** [vuestorefront/shopify#132] opened 2022-01-04 02:37 UTC
### Actual Behavior

display the web page server error, in backend, the server display some error log
ERROR  Cannot read properties of null (reading 'sku')                                                                                                                               02:31:03

  at Object.getItemSku (src/getters/cartGetters.ts:53:0)
  at server.js:17841:1987
  at a.ve [as _l] (/home/ec2-user/work/jizhan/ui/shopify/node_modules/vue/dist/vue.runtime.common.prod.js:6:15953)
  at a.CartSidebarvue_type_template_id_30531c26_render (_theme/components/CartSidebar.vue)
  at /home/ec2-user/work/jizhan/ui/shopify/node_modules/@vue/composition-api/dist/vue-composition-api.common.prod.js:16:12483
  at qt (/home/ec2-user/work/jizhan/ui/shopify/node_modules/@vue/composition-api/dist/vue-composition-api.common.prod.js:16:11840)
  at a.r.render (/home/ec2-user/work/jizhan/ui/shopify/node_modules/@vue/composition-api/dist/vue-composition-api.common.prod.js:16:12454)
  at a.t._render (/home/ec2-user/work/jizhan/ui/shopify/node_modules/vue/dist/vue.runtime.common.prod.js:6:35346)
  at /home/ec2-user/work/jizhan/ui/shopify/node_modules/vue-server-renderer/build.prod.js:1:70854
  at processTicksAndRejections (node:internal/process/task_queues:96:5)

### What version of shopify integration are you using?

main branch

### What version of Node.js are you using?

v16.13.0

### What browser (and version) are you using?

96.0.4664.55

### What operating system (and version) are you using?

linux  

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpdotone** [comment] 2022-03-08 00:17
We're refactoring and updating our cart modules to use the latest Shopify Storefront API. This is one of the issues we'll be tackling with that. Closing this as a duplicate of the refactoring issue. Thank you for submitting this issue.

**Closed by jeffpdotone** 2022-03-08 00:17 UTC
Labels: bug
